# Generated by Django 6.0.4 on 2026-09-15 12:57

import django.db.models.deletion
import horilla.contrib.form_layouts.registry
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0010_alter_recyclebin_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormLayoutField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional Info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=255, verbose_name="Field"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Show on Create Form"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=0, verbose_name="Sequence"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=horilla.contrib.form_layouts.registry.limit_content_types,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.horillacontenttype",
                        verbose_name="Model",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Layout Field",
                "verbose_name_plural": "Form Layout Fields",
                "ordering": ["content_type__model", "sequence", "pk"],
                "unique_together": {("content_type", "field_name", "company")},
            },
        ),
    ]
