# Generated by Django 6.0.4 on 2026-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0003_alter_customfielddefinition_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Value"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date and Time Value"
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("small_text", "Small Text"),
                    ("large_text", "Large Text"),
                    ("number", "Number"),
                    ("choice", "Multiple Choice"),
                    ("single_choice", "Single Choice"),
                    ("date", "Date"),
                    ("datetime", "Date and Time"),
                ],
                max_length=20,
                verbose_name="Field Type",
            ),
        ),
    ]
